#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the cutTheSticks function below.
def cutTheSticks(arr,n):
    arr.sort()
    li=[]
    i=0
    while(i<n):
        li.append(n-i)
        i+=arr.count(arr[i])
    return li
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = cutTheSticks(arr,n)
    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
