#!/bin/python3
import math
import os
import random
import re
import sys
def pickingNumbers(a):
    a.sort()
    res = 0
    for i in range(max(a)):
        res = max(res, a.count(i) + a.count(i+1))
    return res
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')
    n = int(input().strip())
    a = list(map(int, input().rstrip().split()))
    result = pickingNumbers(a)
    fptr.write(str(result) + '\n')
    fptr.close()