#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the saveThePrisoner function below.
def saveThePrisoner(n, m, s):
    u=m%n
    if(u!=0):
        print(u)
        print(s+u-1)
        if(s+u-1<=n):
            return s+u-1
        else:
            return (s+u-1)-n
    else:
        if(s-1==0):
            return n
        else:
            return s-1
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        nms = input().split()

        n = int(nms[0])

        m = int(nms[1])

        s = int(nms[2])

        result = saveThePrisoner(n, m, s)

        fptr.write(str(result) + '\n')

    fptr.close()
