#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the serviceLane function below.
def serviceLane(n, cases):
    liss=[]
    lis=[]
    print(width)
    for j in range(t):
        li=[]
        li=width[cases[j][0]:cases[j][-1]+1]
        liss.append(li)
    print(liss)
    for j in range(t):
        #for k in range(len(liss[j])):
        lis.append(min(liss[j]))
    print(lis)
    return lis
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nt = input().split()

    n = int(nt[0])

    t = int(nt[1])

    width = list(map(int, input().rstrip().split()))

    cases = []

    for _ in range(t):
        cases.append(list(map(int, input().rstrip().split())))
    result = serviceLane(n, cases)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
